
weather:
  midas:
    version: "202407"
    tables:
      TD: []
  cache_dir: "data/raw/archive/weather"
  cache_format: "csv"
timetable:
  api: ""
  url: ""
  input: "data/raw/incoming/timetable"
  cache: "data/raw/archive/timetable"
  cache_format: "csv"
delay:
  api: ""
  url: ""
  input: "data/raw/incoming/delay"
  cache: "data/raw/archive/delay"
  cache_format: "csv"
geospatial:
  location_code: "STANOX"
  max_distance_m: 1000
  seg_len_mi:  8
  api: ""
  url: ""
  input: ""
  cache: "data/raw/archive/geospatial_buckets_mapping.csv" 
ref:
  netrail_loc:
    api: ""
    url: ""
    input: "data/raw/incoming/bplan.zip"
    cache: "data/raw/archive/netrail_loc.csv"
  corpus:
    api: ""
    url: ""
    input: "data/raw/incoming/corpus.zip"
    cache: "data/raw/archive/corpus.csv"
  bank_holiday:
    api: ""
    url: "https://www.gov.uk/bank-holidays.json"
    input: ""
    cache: "data/raw/archive/bank_holiday.json"
  track_model:
    api: ""
    url: ""
    input: "data/raw/incoming/NWR_Track_model.zip"
    cache: ""


