dataset:
  parquet: "data/interim/features"
model:
  type: "poisson"
  formula: "count ~ weather + train_counts"
  offset: null
output_dir: "models/"
train:
  start: "2024-01-01"
  end: "2024-06-30"
test:
  start: "2024-07-01"
  end: "2024-07-31"
simulation:
  draws: 100
  seed: 0